api_version = "2024-01"

[[extensions]]
# Change the merchant-facing name of the extension in locales/en.default.json
name = "t:name"
handle = "hydrogen-reviews-admin-block"
type = "ui_extension"
[[extensions.targeting]]
module = "./src/BlockExtension.tsx"
# The target used here must match the target used in the module file (./src/BlockExtension.tsx)
target = "admin.product-details.block.render"


# Valid extension targets:
# - admin.customer-details.block.render
# - admin.order-details.block.render
# - admin.product-details.block.render
